feat(benchmarking): working benchmarking extrinsic indexing
agicommies/subspace-network pull request #109
Opened 2024-05-19 11:45 UTC by Supremesource

This PR:
- adds the ability to run benchmarks for all mainnet extrinsic calls
- it completely deletes the old benchmarking replacing it with new logic.
- indexes extrinsic calls 
- adding expected weight consumption to every extrinsic

Renaming: 
- `autogen_weights` -> `weights`
- `weights` -> `set_weights`
Closes #107

2024-05-19 18:43 UTC, devwckd commented on node/src/service.rs
> +#[allow(dead_code)]
What is this used for?

Non blocking

2024-05-19 18:46 UTC, Supremesource commented on node/src/service.rs
> +#[allow(dead_code)]
Oh, I will delete this

2024-05-19 20:16 UTC, devwckd approved these changes
LGTM

2024-05-20 14:56 UTC, saiintbrisson requested changes

2024-05-20 14:56 UTC, saiintbrisson commented on node/src/main.rs
> +// #[cfg(feature = "runtime-benchmarks")]
is this correct?

2024-05-20 14:56 UTC, saiintbrisson commented on Makefile
> +	./target/release/node-subspace benchmark pallet --chain specs/benchmarks.json --pallet pallet_subspace --extrinsic "*" --steps 50 --repeat 20 --output pallets/subspace/src/weights.rs --template=./.m
it's missing a new line here

2024-05-20 15:19 UTC, Supremesource commented on node/src/main.rs
> +// #[cfg(feature = "runtime-benchmarks")]
yes

2024-05-20 16:24 UTC, merged