feat(pallets/subpsace): convert stake data type into dmaps
agicommies/subspace-network pull request #120
Opened 2024-05-30 21:00 UTC by aripiprazole

Converts StakeFrom and StakeTo data into a new double storage map

2024-05-30 21:47 UTC, saiintbrisson requested changes

2024-05-30 21:47 UTC, saiintbrisson commented on pallets/subspace/src/staking.rs
> +            .collect()
```suggestion
        StakeTo::<T>::iter_prefix(key).collect()
```

2024-05-30 21:47 UTC, saiintbrisson commented on pallets/subspace/src/staking.rs
> +                StakeTo::<T>::insert(to, key, v);
```suggestion
            for (to, v) in stake_to_vector.into_iter() {
                StakeTo::<T>::insert(key, to, v);
```

2024-05-30 21:47 UTC, saiintbrisson commented on pallets/subspace/src/staking.rs
> +        StakeTo::<T>::iter_prefix(module_key).collect::<BTreeMap<_, _>>()
```suggestion
        StakeFrom::<T>::iter_prefix(module_key).collect()
```

2024-06-28 21:37 UTC, Supremesource commented
Solved on global-stake-v2

2024-06-28 21:37 UTC, closed without merging