refac(pallets/subpsace): use dispatch results
agicommies/subspace-network pull request #141
Opened 2024-06-16 19:56 UTC by aripiprazole

2024-06-20 18:26 UTC, Supremesource requested changes

2024-06-20 18:26 UTC, Supremesource commented on pallets/subspace/src/step.rs
> +                    None => Err(Error::<T>::ExtrinsicPanicked)?,
```suggestion
                    None => Err(Error::<T>::StepPanicked)?,
```

2024-06-20 18:26 UTC, Supremesource commented on pallets/subspace/src/step.rs
> +                    None => Err(Error::<T>::ExtrinsicPanicked)?,
```suggestion
                    None => Err(Error::<T>::StepPanicked)?,
```

2024-06-27 17:54 UTC, devwckd commented on pallets/subspace/src/math.rs
> +                continue;
Shouldn't this return a result instead of continuing if the vectors aren't the expected size? There's a small chance of it happening but if it does, we'd never know, and the chain would operate on wrong numbers. (Counts for the other similar cases as well)

2024-06-27 18:18 UTC, Supremesource commented
Move the 
```toml
[lints.clippy]
arithmetic_side_effects = "deny"
indexing_slicing = "deny"
panicking_unwrap = "deny"
out_of_bounds_indexing = "deny"
```
To the root of the `Cargo.toml`

2024-06-28 16:33 UTC, Supremesource requested changes
Move the 
```toml
[lints.clippy]
arithmetic_side_effects = "deny"
indexing_slicing = "deny"
panicking_unwrap = "deny"
out_of_bounds_indexing = "deny"
```
To the root of the `Cargo.toml`

2024-06-28 21:44 UTC, Supremesource approved these changes
LGTM

2024-06-29 05:35 UTC, saiintbrisson commented
@aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?

2024-06-29 05:41 UTC, aripiprazole commented
> @aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?

I can rebase on top of `feat/global-stake-v2` tomorrow. I think it will be done more quickly if I do this.

2024-06-29 07:25 UTC, Supremesource commented
> > @aripiprazole as with the ongoing development on `feat/global-stake-v2`, this will be a massive headache if we merge it now. You have two options: rebasing this on top of `feat/global-stake-v2` and merge it to that branch, or waiting until we merge it main first. Which one do you wanna go with?
> 
> I can rebase on top of `feat/global-stake-v2` tomorrow. I think it will be done more quickly if I do this.

Yes ! Please rebase it there, at least we will have it in the tests already

2024-07-01 11:59 UTC, merged