feat: add validator blacklist
agicommies/subspace-network pull request #202
Opened 2024-08-16 01:30 UTC by devwckd

# Pull Request Checklist

Before submitting this PR, please make sure:

- [ ] You have run `cargo clippy` and addressed any warnings
- [ ] You have added appropriate tests (if applicable)
- [ ] You have updated the documentation (if applicable)
- [ ] You have reviewed your own code
- [ ] You have updated changelog (if applicable)

## Description

Please provide a brief description of the changes in this PR.

## Related Issues

Please link any related issues here

2024-08-16 01:31 UTC, devwckd commented
@Supremesource or @saiintbrisson pls run benchmarks for me and fix the pallet calls if possible, I cant run them, thanks :D

2024-08-19 00:16 UTC, Supremesource requested changes
Fix the ensures please. Also you need to check if the person calling both extrinsic is acutally a subnet owner of that netuid, you don't do this now

2024-08-19 00:16 UTC, Supremesource commented on pallets/subspace/src/subnet.rs
> +        ensure!(
remove this check, you can blacklist it even when it's not registered

2024-08-19 00:16 UTC, Supremesource commented on pallets/subspace/src/subnet.rs
> +            Uids::<T>::get(netuid, &module).is_some(),
remove it here as well

2024-08-19 21:06 UTC, devwckd commented
> Fix the ensures please. Also you need to check if the person calling both extrinsic is acutally a subnet owner of that netuid, you don't do this now

@Supremesource  doesn't this work?

```
        let params = Self::subnet_params(netuid);
        ensure!(params.founder == key, Error::<T>::NotFounder);
```

2024-08-20 10:45 UTC, Supremesource commented
> > Fix the ensures please. Also you need to check if the person calling both extrinsic is acutally a subnet owner of that netuid, you don't do this now
> 
> @Supremesource doesn't this work?
> 
> ```
>         let params = Self::subnet_params(netuid);
>         ensure!(params.founder == key, Error::<T>::NotFounder);
> ```

Oh, yeah, it does, I must have missed that

2024-08-20 10:46 UTC, merged