refac(pallets/subspace): making code more robust
agicommies/subspace-network pull request #38
Opened 2024-03-16 18:42 UTC by Supremesource

Simplifying the code, fixing clones, making more readable

2024-03-16 20:53 UTC, aripiprazole commented
I would rename the title so the name of the squash commit would be more explicit

2024-03-16 21:11 UTC, aripiprazole requested changes

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/src/step.rs
> +    fn calculate_emissions(
Why do you removed the comments?

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/src/step.rs
> +        if weight_age > subnet_params.max_weight_age
Use if return instead of nesting if-elses

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/src/step.rs
> +            if founder_share > 0 {
The same thing here with nested ifs

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/src/weights.rs
>          if sum == 0 {
Remove this if

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/tests/profit_share.rs
I think we should replace this prints with asserts instead of just replacing with logs

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/tests/profit_share.rs
But this can be left for further and another PRs

2024-03-16 21:11 UTC, aripiprazole commented on pallets/subspace/tests/weights.rs
> -/// Check _falsey_ path for weights length
Why removing these tests?

2024-03-16 21:59 UTC, Supremesource commented on pallets/subspace/tests/weights.rs
> -/// Check _falsey_ path for weights length
I had to take them out because I simplified the code a lot, getting rid of the small helper functions they were using. 
 
The whole logic is implemented in few lines, namely :
- `    ensure!(!uids.contains(&uid), Error::<T>::NoSelfWeight);` 
- ```rs
    let min_allowed_length: usize = Self::get_min_allowed_weights(netuid) as usize;
        let max_allowed_length: usize = Self::get_max_allowed_weights(netuid) as usize;
        ensure!(
            uids.len() >= min_allowed_length && uids.len() <= max_allowed_length,
            Error::<T>::InvalidUidsLength
        );```
    
There is pretty much no place for error, I will re-implement the tests later, trying to achieve the same thing they did before but calling straight the `do_set_weights`.

2024-03-16 21:59 UTC, Supremesource commented on pallets/subspace/src/weights.rs
>          if sum == 0 {
are you sure ? If there will be the 0 division it will panic
```rs
    if sum == 0 {
            return weights;
        }
        weights
            .into_iter()
            .map(|x| ((x as u64 * u16::max_value() as u64) / sum) as u16)
            .collect()
    }
```

2024-03-16 22:17 UTC, Supremesource commented on pallets/subspace/src/step.rs
> +    fn calculate_emissions(
Yeah, I will add most of them back

2024-03-16 22:17 UTC, Supremesource commented on pallets/subspace/src/step.rs
> +    fn calculate_emissions(
to be honest, most of them are even wrong or very obvious from the syntax. I would consider doing standalone comment PR later, but atm it's not the most relevant thing

2024-03-16 22:19 UTC, Supremesource commented
d4b3f23ac9f3c04a11303dfed02a7aadc02e702b
@aripiprazole Applied most of the things you asked for

2024-03-17 00:46 UTC, saiintbrisson requested changes

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/global.rs
> -    // TODO: make sure there are checks for all values
Was this addressed?

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/global.rs
> +        Self::check_global_params(params.clone()).unwrap();
I'm pretty sure `check_global_params` could receive `&GlobalParams` instead and avoid cloning it here.

Change it to an expect statement. Unwraps are usually unhelpful.
```suggestion
        Self::check_global_params(params.clone()).expect("global params are invalid");
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/lib.rs
Were the storage items removed or relocated? I can't find `Key2Controller`. This will most probably mess with the genesis building stage, was this tested?

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/math.rs
> +    sparse_matrix.iter_mut().for_each(|sparse_row| {
A `for` statement is the idiomatic way to do this here, we can leave it the way it was

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/profit_share.rs
> +                normalized_share
```suggestion
                (share as u64 * u16::MAX as u64 / total_shares as u64) as u16
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/profit_share.rs
> +            keys.into_iter().zip(adjusted_shares.into_iter()).collect();
```suggestion
            keys.into_iter().zip(adjusted_shares).collect();
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/registration.rs
>          module_key: T::AccountId, // module key
The comments here are unnecessary.
```rust
        network_name: Vec<u8>,
        module_name: Vec<u8>,
        module_address: Vec<u8>,
        stake_amount: u64,
        module_key: T::AccountId,
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/src/step.rs
Change all `&Vec<_>` to `&[_]`

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/tests/delegate_staking.rs
> +            info!("DELEGATE KEY: {}", d);
```suggestion
            info!("DELEGATE KEY: {d}");
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/tests/delegate_staking.rs
> +        info!("total_tokens_before: {:?}", total_tokens_before);
```suggestion
        info!("total_tokens_before: {total_tokens_before:?}");
```

2024-03-17 00:46 UTC, saiintbrisson commented on pallets/subspace/tests/delegate_staking.rs
> +        info!("delegate_stakes before: {:?}", delegate_stakes_before);
Do the same everywhere else

```suggestion
        info!("delegate_balances before: {delegate_balances_before:?}");
        info!("delegate_stakes before: {delegate_stakes_before:?}");
```

2024-03-17 10:30 UTC, Supremesource commented
@saiintbrisson 
14e5e6553ef5d3f7b296ce033f6d6f5664850e86
I did the refactors you requested

2024-03-17 15:52 UTC, aripiprazole commented on pallets/subspace/src/module.rs
> +        let _delegation_fee: Percent = DelegationFee::<T>::get(netuid, &uid_key);
Is this used?

2024-03-17 15:55 UTC, aripiprazole commented on pallets/subspace/src/module.rs
```diff
-        log::debug!(
-            "append_module( netuid: {:?} | uid: {:?} | new_key: {:?} ) ",
-            netuid,
-            key,
-            uid
-        );
+        log::debug!("append_module( netuid: {netuid:?} | uid: {key:?} | new_key: {uid:?} )")
```

2024-03-17 15:59 UTC, aripiprazole commented on pallets/subspace/src/weights.rs
>          if sum == 0 {
ah, makes sense

2024-03-17 15:59 UTC, aripiprazole commented on pallets/subspace/src/weights.rs
> -        weights.iter_mut().for_each(|x| {
use for instead of for_each

2024-03-17 16:25 UTC, Supremesource commented
@aripiprazole 
74d279f9c662c1bac95cab9d125e59fcd57d55b8
refac

2024-03-17 16:33 UTC, aripiprazole approved these changes

2024-03-17 21:24 UTC, saiintbrisson commented on pallets/subspace/src/global.rs
> -    // TODO: make sure there are checks for all values
@Supremesource

2024-03-18 19:05 UTC, saiintbrisson approved these changes

2024-03-18 19:06 UTC, merged