feat: making code more robust, fixing incentives
agicommies/subspace-network pull request #44
Opened 2024-03-31 22:29 UTC by Supremesource

# Changes
- local subnet burn + migration
- ensuring name safety regarding subnet naming
- fixing exploit-ability after reaching global maximum of modules

I honestly think that we should change the `subneset` to `subnetchangeset` and also add the update for it, what do you think @saiintbrisson ?

2024-03-31 22:48 UTC, saiintbrisson requested changes
It's good practice to unify all validations in a single place. This makes searching for bugs a LOT easier in the future. Avoid writing security-crucial code more than once in the same codebase, prefer reusing functions

2024-03-31 22:48 UTC, saiintbrisson commented on pallets/subspace/src/subnet.rs
> +pub struct SubnetSet<T: Config> {
```suggestion
pub struct SubnetChangeset<T: Config> {
```

2024-03-31 22:48 UTC, saiintbrisson commented on pallets/subspace/src/subnet.rs
> +    pub fn new(name: &Vec<u8>, founder_key: &T::AccountId, params: SubnetParams<T>) -> Self {
```suggestion
    pub fn new(name: &[u8], founder_key: &T::AccountId, params: SubnetParams<T>) -> Self {
```

2024-03-31 22:48 UTC, saiintbrisson commented on pallets/subspace/src/subnet.rs
> +                !Pallet::<T>::if_subnet_name_exists(&name),
As for the module, this must only be checked if the subnet name is different from its current name. Check `ModuleChangeset::new` to see how it's done.

2024-03-31 22:48 UTC, saiintbrisson commented on pallets/subspace/src/subnet.rs
> +            );
Doing this will make this changeset only work when updating a subnet, and not registering one, meaning the same validations will have to be re-done elsewhere, which fragments validation logic.

2024-04-01 04:44 UTC, aripiprazole commented on pallets/subspace/src/step.rs
> +            Self::set_burn(
I would split on a variable just to make easier to read

2024-04-01 04:47 UTC, aripiprazole approved these changes

2024-04-02 11:28 UTC, saiintbrisson approved these changes

2024-04-02 11:35 UTC, merged