feat(pallets/subspace): add arbitrary uri parameter
agicommies/subspace-network pull request #48
Opened 2024-04-12 23:26 UTC by aripiprazole

2024-04-15 18:41 UTC, steinerkelvin commented
When I said "arbitrary URI" it was just a description of what would go in the field 😅

The field should be named `metadata` or `metadata_uri` or something like that. @saiintbrisson

2024-04-16 14:39 UTC, saiintbrisson requested changes
Rename it as kelvin said and you have to add a way to change the metadata too. Look into how `ModuleChangeset` works

2024-04-16 14:39 UTC, saiintbrisson commented on pallets/subspace/src/lib.rs
> +
```suggestion
    #[pallet::storage] // --- DMAP ( netuid, uid ) --> module_address
    pub type ArbitraryUri<T: Config> =
        StorageDoubleMap<_, Twox64Concat, u16, Twox64Concat, u16, Vec<u8>>;

```

2024-04-16 14:39 UTC, saiintbrisson commented on pallets/subspace/src/lib.rs
> +        pub arbitrary_uri: Vec<u8>,
```suggestion
        pub arbitrary_uri: Option<Vec<u8>>,
```

2024-04-16 14:49 UTC, steinerkelvin commented
Also, this field should have a limited size. Max 256 bytes or so, so people don't dump Shakespeare inside the module metadata. Just enough for a secure hash/id/uri of the content.


According to the oracle (Claude):

> The maximum size of an IPFS CID (Content Identifier) string depends on the CID version and the multibase encoding used. Here are the details:
> 
> CID Version 0 (CIDv0):
> 
> CIDv0 uses base58btc encoding.
> The maximum length of a CIDv0 string is 46 characters.
> Example: QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG
> CID Version 1 (CIDv1):
> 
> CIDv1 supports various multibase encodings, but the most commonly used are base32 and base58btc.
> The maximum length of a CIDv1 string depends on the multibase encoding:
> base32: The maximum length is 62 characters.
> Example: bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq
> base58btc: The maximum length is 59 characters.
> Example: zdj7WWeQ43G6JJvLWQWZpyHuAMq6uYWRjkBXFad11vE2LHhQ7
> It's important to note that the actual length of a CID string can vary depending on the content being addressed and the specific multicodec and multihash used within the CID.
> 
> In summary, the maximum size of an IPFS CID string is:
> 
> CIDv0 (base58btc): 46 characters
> CIDv1 (base32): 62 characters
> CIDv1 (base58btc): 59 characters

https://github.com/multiformats/cid#decoding-algorithm

https://cid.ipfs.tech/#bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq

2024-04-17 13:44 UTC, aripiprazole commented
> Rename it as kelvin said and you have to add a way to change the metadata too. Look into how `ModuleChangeset` works

Should I add it into changeset struct?

2024-04-17 13:48 UTC, aripiprazole commented
> Also, this field should have a limited size. Max 256 bytes or so, so people don't dump Shakespeare inside the module metadata. Just enough for a secure hash/id/uri of the content.
> 
> According to the oracle (Claude):
> 
> > The maximum size of an IPFS CID (Content Identifier) string depends on the CID version and the multibase encoding used. Here are the details:
> > CID Version 0 (CIDv0):
> > CIDv0 uses base58btc encoding.
> > The maximum length of a CIDv0 string is 46 characters.
> > Example: QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG
> > CID Version 1 (CIDv1):
> > CIDv1 supports various multibase encodings, but the most commonly used are base32 and base58btc.
> > The maximum length of a CIDv1 string depends on the multibase encoding:
> > base32: The maximum length is 62 characters.
> > Example: bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq
> > base58btc: The maximum length is 59 characters.
> > Example: zdj7WWeQ43G6JJvLWQWZpyHuAMq6uYWRjkBXFad11vE2LHhQ7
> > It's important to note that the actual length of a CID string can vary depending on the content being addressed and the specific multicodec and multihash used within the CID.
> > In summary, the maximum size of an IPFS CID string is:
> > CIDv0 (base58btc): 46 characters
> > CIDv1 (base32): 62 characters
> > CIDv1 (base58btc): 59 characters
> 
> https://github.com/multiformats/cid#decoding-algorithm
> 
> https://cid.ipfs.tech/#bafybeiemxf5abjwjbikoz4mc3a3dla6ual3jsgpdr4cjr3oz3evfyavhwq

@steinerkelvin Where do I put the validation here? Is it only when we are trying to update (aka ModuleChangeset) or there's another place to add it?

2024-04-17 13:55 UTC, steinerkelvin commented
> @steinerkelvin Where do I put the validation here? Is it only when we are trying to update (aka ModuleChangeset) or there's another place to add it?

Oh, this was just a discussing size. The only validation subspace-side should be that it's a valid UTF8 string, and the size limit.

2024-04-17 14:03 UTC, saiintbrisson commented
> Where do I put the validation here?
 
On the apply function of ModuleChangeset

2024-04-17 17:09 UTC, merged