feat: making s0 applications more robust
agicommies/subspace-network pull request #62
Opened 2024-04-29 22:25 UTC by Supremesource

Can we guys write tests as well please ? I truly speedrun the whole thing

2024-04-30 14:57 UTC, saiintbrisson requested changes

2024-04-30 14:57 UTC, saiintbrisson commented on pallets/subspace/src/migrations.rs
> +                let dao_bot_account_id = ss58_to_account_id::<T>(dao_bot).unwrap();
@Supremesource this will brick the chain if it fails for some reason, prefer adding a `if let Err(err) = ... { log::error!("etc"); }`

2024-04-30 17:23 UTC, Supremesource reviewed
I am putting this on testnet

2024-05-01 04:54 UTC, saiintbrisson approved these changes

2024-05-01 04:54 UTC, merged