feat(pallets/subspace): add faucet function
agicommies/subspace-network pull request #95
Opened 2024-05-10 11:57 UTC by aripiprazole

2024-05-10 12:04 UTC, Supremesource commented on pallets/subspace/src/lib.rs
> +            if cfg!(test) {
rename this to testnet

2024-05-10 12:04 UTC, Supremesource commented on pallets/subspace/src/registration.rs
> +    pub fn hash_block_and_hotkey(block_hash_bytes: &[u8; 32], hotkey: &T::AccountId) -> H256 {
rename everything from hotkey to just `key` commune does not have hotkeys

2024-05-13 17:01 UTC, saiintbrisson requested changes

2024-05-13 17:01 UTC, saiintbrisson commented on runtime/src/lib.rs
> +
@aripiprazole I don't think we need this anymore?

2024-05-13 17:01 UTC, saiintbrisson commented on pallets/subspace/tests/mock.rs
> +
Or this

2024-05-13 21:53 UTC, saiintbrisson approved these changes

2024-05-13 21:53 UTC, merged